source 'https://rubygems.org'


gem 'rails', '4.1.8'
gem 'sqlite3'
gem 'sass-rails', '~> 4.0.3'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0',          group: :doc
gem 'spring',        group: :development
gem 'devise'
gem 'webpay'
gem 'rb-readline'
group :production do
  gem 'mysql2'
end
group :test do
    gem 'capybara'
    gem 'capybara-user_agent'
    gem 'database_cleaner'
    gem 'factory_girl_rails', group: :development
    gem 'rspec-rails', group: :development
    gem 'spring-commands-rspec'
end


